RESTORE DATABASE AwExamenBDII 
FROM TareaDevice 
WITH FILE = 1, 
    MOVE N'AdventureWorks2019_Data_Data' TO N'D:\DESTINITATIONDISK\MSSQL2019\\DATA\AwExamenBDII_Data.mdf', 
	MOVE N'AdventureWorks2019_Data_Data_2' TO N'D:\DESTINITATIONDISK\MSSQL2019\\DATA\AwExamenBDII.mdf', 
	MOVE N'AdventureWorks2019_Data_Data_3' TO N'D:\DESTINITATIONDISK\MSSQL2019\\DATA\AwExamenBDII_3.mdf', 
	MOVE N'AdventureWorks2019_Data_Data_4' TO N'D:\DESTINITATIONDISK\MSSQL2019\\DATA\AwExamenBDII_4.mdf', 
	MOVE N'AdventureWorks2019_Data_Data_5' TO N'D:\DESTINITATIONDISK\MSSQL2019\\DATA\AwExamenBDII_5.mdf', 
    MOVE N'AdventureWorks2019_Data_Log_1' TO N'D:\DESTINITATIONDISK\MSSQL2019\\LOG\AwExamenBDII_Log_1.ldf', 
	MOVE N'AdventureWorks2019_Data_Log_2' TO N'D:\DESTINITATIONDISK\MSSQL2019\\LOG\AwExamenBDII_Log_2.ldf', 
NOUNLOAD, REPLACE, STATS = 10
GO